INFERANALYZE= /usr/local/Cellar/infer/0.11.0/lib/infer/infer/bin/InferAnalyze --results-dir '/Users/laurarundle/Desktop/gymtimerepo/infer-out' --compilation-database-escaped '/Users/laurarundle/Desktop/gymtimerepo/infer-out/clang/cdb9ab6f3.json' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
